# ID: 584 - Return Inside Finally Block
<h5>Name</h5>Return Inside Finally Block
<h5>Weakness</h5>Base
<h5>Status</h5>Draft
<h5>Description</h5>The code has a return statement inside a finally block, which will cause any thrown exception in the try block to be discarded.
<h5>ExtendedDescription</h5>null
<h5>RelatedWeaknesses</h5>::NATURE:ChildOf:CWE ID:705:VIEW ID:1000:ORDINAL:Primary::
<h5>WeaknessOrdinalities</h5>null
<h5>ApplicablePlatforms</h5>null
<h5>BackgroundDetails</h5>null
<h5>AlternateTerms</h5>null
<h5>ModesOfIntroduction</h5>:::PHASE:Implementation:DESCRIPTION:::
<h5>ExploitationFactors</h5>null
<h5>LikelihoodofExploit</h5>null
<h5>CommonConsequences</h5>::SCOPE:Other:TECHNICAL IMPACT:Alter Execution Logic::
<h5>DetectionMethods</h5>null
<h5>PotentialMitigations</h5>::PHASE:Implementation:STRATEGY::EFFECTIVENESS::DESCRIPTION:Do not use a return statement inside the finally block. The finally block should have cleanup code.::
<h5>ObservedExamples</h5>null
<h5>FunctionalAreas</h5>null
<h5>AffectedResources</h5>null
<h5>TaxonomyMappings</h5>TAXONOMY NAME:CERT Java Secure Coding:ENTRY ID:ERR04-J:ENTRY NAME:Do not complete abruptly from a finally block::::TAXONOMY NAME:CERT Java Secure Coding:ENTRY ID:ERR05-J:ENTRY NAME:Do not let checked exceptions escape from a finally block::::TAXONOMY NAME:Software Fault Patterns:ENTRY ID:SFP6:ENTRY NAME:Incorrect Exception Behavior::
<h5>RelatedAttackPatterns</h5>null
<h5>Notes</h5>null

